### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jmewes**

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @jmewes 😊

**Comment by jmewes** [comment]
@dkayiwa you are most welcome.

One additional remark regarding this developer manual:

It seems like there is a lot of overlap between the [Confluence page]() describing the SDK and the Developer Manual book. It might be a good idea to consolidate this so that it doesn't need to be maintained at two places.

What is the intension behind the information in the Developer Manual? What is the intension behind the information in the Wiki?

**Comment by dkayiwa** [comment]
Very good question. Do you mind raising this on Talk?

**Comment by jmewes** [comment]
Here you go: https://talk.openmrs.org/t/documentation-duplicated-description-of-openmrs-developer-sdk/12177

**Pull request merged**
