### PR TITLE
DOCUMENTATION FORUM : updated the "create your module page" to in an …

### PR DESCRIPTION
**Pull request by mozzy11**
DocumentationForum : Updated the "create your first module" section to include "adding test units and  modifying the messages.property file"

### CODE REVIEW

**Comment by jwnasambu** [comment]
@mozzy11 kindly help point out the changes you made.

**Comment by mozzy11** [comment]
HI @jwnasambu  https://github.com/openmrs/openmrs-book-developer-manual/pull/12/commits/aa991ae39c78d95aa3b16ddd50fe4bcb2008f260

**Comment by mozzy11** [comment]
@jwnasambu  in the section **"create your first module"** , i added the following
* added test units for the example module
* i added the message.properties file modofication forthe example module

**Comment by ibacher** [comment]
Closing this as it should be handled as part of the on-going GSOD projects.

**Pull request closed without merging**
