### PR TITLE
Trunk 4213

### PR DESCRIPTION
**Pull request by mozzy11**
Documentation forum.

Updated the create your first module page to in clude "Adding test units " and "Updating the message.properties file " for the example

### CODE REVIEW

**Review by tendomart — COMMENTED** [review]
@mozzy11  There are unnecessary spaces i noticed in "DerpartmentServiceTest " ,spelling mistakes

**Review by Ruhanga — COMMENTED** [review]
@mozzy11 , can you add the JIRA link to the ticket as advised here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by mozzy11** [comment]
@tendomart  , i tried to work on the unnecessary spaces and spelling mistakes.
@Ruhanga thanks. but just that innitially this wasnt intended to be attached to any ticket. it was for the documentation forum

**Review by Ruhanga — COMMENTED** [review]
What is the meaning of  "Trunk 4213" ?

**Comment by mozzy11** [comment]
@Ruhanga i understand your point. the issue is peviously i had worked on a ticket to modify the developer manual and the commits were merged. Now i have just added more commits on the previous PR that was merged , though these new commits are not necesarily part of the ticket I previously worked on , they are for the documentation forum

**Comment by mozzy11** [comment]
i think  it was a mistake , i was just supposed to completely create a new branch for these commits

**Comment by mozzy11** [comment]
but either way. they are going to be merged to the same destination anyway

**Comment by mozzy11** [comment]
hello , ive closed this PR . please refer to this now
 https://github.com/openmrs/openmrs-book-developer-manual/pull/12

**Pull request closed without merging**
