### PR TITLE
Fixing link to atlas in 'OpenMRS Today' chapter

### PR DESCRIPTION
**Pull request by michalfotyga**
It now points to the corrent page

### CODE REVIEW

**Comment by michalfotyga** [comment]
Actually more links are broken, but I don't know what to change them to.
They are in 'Working Cooperatively' chapter:
- http://om.rs/newdev-bikeshed
- http://om.rs/newdev-choose

**Comment by dkayiwa** [comment]
Thanks @michalfotyga 👍 
Can you share the other broken links?

**Comment by bmamlin** [comment]
Thanks @michalfotyga for spotting the broken links. When creating the book, they made "newdev" shortlinks for the book to help track usage of the book. When we translated shortlinks from the old (deprecated) `go.openmrs.org` form to `om.rs`, the new shortlinks do not allow hyphens, so these can be corrected by removing the hyphens (e.g., http://om.rs/newdev-bikeshed &rarr; http://om.rs/newdevbikeshed).

**Comment by michalfotyga** [comment]
Ah, nice! Thanks for the explanation @bmamlin. And I see you have already updated other links 👌

**Pull request merged**
